name: Build Mac

on: [push]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install pyinstaller pypdf Pillow reportlab pdf2image

      - name: Instalar poppler
        run: brew install poppler

      - name: Compilar .app
        run: |
          pyinstaller --windowed --onedir --name "AquaMark" \
            --add-binary "$(brew --prefix poppler)/bin/pdftoppm:." \
            --add-binary "$(brew --prefix poppler)/bin/pdfinfo:." \
            Marca.py
          
          # Dar permisos correctos
          chmod -R +x dist/AquaMark.app
          
          # Quitar cuarentena desde origen
          xattr -cr dist/AquaMark.app

      - name: Comprimir .app
        run: |
          cd dist
          zip -r AquaMark-Mac.zip AquaMark.app

      - name: Subir ejecutable
        uses: actions/upload-artifact@v4
        with:
          name: AquaMark-Mac
          path: dist/AquaMark-Mac.zip
